# Generated by Django 2.2.4 on 2021-04-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=45)),
                ('companyName', models.CharField(max_length=45)),
                ('streetAddress', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=45)),
                ('zipCode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
