# Generated by Django 2.2.4 on 2021-07-08 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=40, null=True)),
                ('password', models.CharField(max_length=45, null=True)),
                ('missionS', models.CharField(max_length=1000, null=True)),
                ('whyLife', models.CharField(max_length=1000, null=True)),
                ('OurGuarantee', models.CharField(max_length=1000, null=True)),
                ('tailorFit', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobLocation', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('prefferedInspectionDate', models.DateTimeField()),
                ('comments', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workRequests', to='inApp.Client')),
            ],
        ),
    ]
