# Generated by Django 2.2.4 on 2020-10-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
