# Generated by Django 2.2.4 on 2021-07-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inApp', '0002_admin_workrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
