# Generated by Django 2.2.4 on 2021-07-08 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inApp', '0003_workrequest_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workrequest',
            old_name='comments',
            new_name='comment',
        ),
    ]
